=== huntriver/CCDB-CSE532-Proj3-/CCDB.xsd
<xs:schema xmlns="http://localhost:8080/exist/CCDB" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost:8080/exist/CCDB">
    <xs:element name="PersonName" type="xs:string"/>
    <xs:element name="PId" type="xs:string"/>
    <xs:element name="OId" type="xs:string"/>
    <xs:element name="CId" type="xs:string"/>
    <xs:element name="Owner" type="xs:string"/>
    <xs:element name="OrgName" type="xs:string"/>
    <xs:element name="Limit" type="xs:decimal"/>
    <xs:element name="Balance" type="xs:decimal"/>
    
    <xs:element name="Person">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="PersonName"/>
                <xs:element ref="PId"/>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CId"/>
                <xs:element ref="Owner"/>
                <xs:element ref="Limit"/>
                <xs:element ref="Balance"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Persons">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Person" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

    </xs:element>  
   

   <xs:element name="Cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Card" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

    </xs:element>  

    <xs:element name="CCDB">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Persons" />
                <xs:element ref="Cards" />
            </xs:sequence>
        </xs:complexType>
        
        <!-- Definition of keys -->
        <xs:key name="PrimaryKeyForPerson">
            <xs:selector xpath="Person"/>
            <xs:field xpath="PId"/>
        </xs:key>

        <xs:key name="PrimaryKeyForCard">
            <xs:selector xpath="Card"/>
            <xs:field xpath="CId"/>
        </xs:key>

        <xs:keyref name="FKOwner" refer="PrimaryKeyForPerson">
            <xs:selector xpath="Card"/>
            <xs:field xpath="Owner"/>
        </xs:keyref>


    </xs:element>
</xs:schema>

=== huntriver/CCDB-CSE532-Proj3-/CCDB.xml
<!--CSE532 Project 3--><!--File name: tss.xml--><!--Author Kin Sum Liu (109247869)--><!--Brief description: This contains all the data we need. --><!--"TSS" is the name of the root element that represents the list of shows--><!--I pledge my honor that all parts of this project were done by me alone and without collaboration with anybody else-->
<CCDB xmlns="http://localhost:8080/exist/CCDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://localhost:8080/exist/CCDB CCDB.xsd">
    <Persons>
        <Person>
            <PersonName>Ann</PersonName>
            <PId>p1</PId>
        </Person>
        <Person>
            <PersonName>John</PersonName>
            <PId>p2</PId>
        </Person>
        <Person>
            <PersonName>Joe</PersonName>
            <PId>p3</PId>
        </Person>
        <Person>
            <PersonName>May</PersonName>
            <PId>p4</PId>
        </Person>
        <Person>
            <PersonName>Bob</PersonName>
            <PId>p5</PId>
        </Person>
        <Person>
            <PersonName>Faye</PersonName>
            <PId>p6</PId>
        </Person>
        <Person>
            <PersonName>Bill</PersonName>
            <PId>p7</PId>
        </Person>
        <Person>
            <PersonName>Sally</PersonName>
            <PId>p8</PId>
        </Person>
        <Person>
            <PersonName>Miriam</PersonName>
            <PId>p9</PId>
        </Person>
        <Person>
            <PersonName>April</PersonName>
            <PId>p10</PId>
        </Person>
    </Persons>
</CCDB>
